### PR TITLE
Look at the schema in accepts optionally

### LINKED ISSUE #7: Explicit schema on enums
Hi, 

following case;
```rust
#[derive(Debug, ToSql, FromSql)]
#[postgres(name="myschema.mood_e")]
pub enum Mood
{
    #[postgres(name="H")]
    Happy,

    #[postgres(name="S")]
    Sad,
}
```
will panic with cannot convert from/to postgresql type. Removing the `myschema` and moving the enumeration into the public schema works like a charm. Unfortunately I have the case of a DB with multiple schemas and it is kind of a bummer having to put everything into a common pool of more often than not unrelated types and enumerations.

Best Regards,
lwk

### PR DESCRIPTION
**Pull request by sfackler**
Closes #7

### CODE REVIEW

**Comment by sfackler** [comment]
I wonder if we should default to `public` and always look at the schema?

cc @lweberk

**Comment by lweberk** [comment]
I'm not entirely sure whether I get your question. You mean to imply `public` –relying on the default PostgreSQL bahaviour– when no schema is provided versus explicitly defaulting to `public`? thus reflecting that in the query?

**Comment by sfackler** [comment]
The specified type name and schema are only used to decide if a Postgres type is compatible with the rust type for deserialization. We currently only check the type name - it can be defined in any schema at all. This PR currently changes things so that you can optionally specify a schema if you want to check that as well. This would only really be relevant if you have multiple types with the same name defined in different schemas. The possible alternative is that we always check the schema, and default to checking that it's in the `public` schema unless otherwise overridden.

**Comment by lweberk** [comment]
Given the possibility –however unlikely– of type name collisions between ones residing within the public schema and otherwise outside of public, I'd feel inclined towards the possible alternative you state. Explicitly checking for the type as if residing in the public schema unless otherwise explicitly overridden in the derive seems to be the scenario with the least surprises.

**Comment by sfackler** [comment]
Changing the schema check to mandatory ironically breaks the testing since `pg_temp` is actually an alias for `pg_temp_1`, `pg_temp_2`, etc and changes per connection.

**Pull request closed without merging**
