### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by hcpl**

### CODE REVIEW

**Comment by sfackler** [comment]
Looks like the minimum supported Rust version needs to be bumped.

**Comment by hcpl** [comment]
`postgres-derive` itself doesn't need bumping, `typenum` is one of `postgres` transitive dependencies and the minimum Rust for `postgres` [is already 1.20](https://github.com/sfackler/rust-postgres/commit/50e17acae627b1cf414dc2692498ae4e617fd7e2).

But does it make sense to keep `postgres-derive` building on versions older than `postgres` is a whole other question...

**Comment by sfackler** [comment]
Seems fine to bump it.

**Comment by sfackler** [comment]
You'll need to switch from `jimmycuadra/rust:1.20.0` to just `rust:1.20.0`.

**Comment by hcpl** [comment]
Thanks for tips! I hope I got that right now.

**Comment by sfackler** [comment]
Thanks!

**Pull request merged**
